<?php

if ( ! defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED !== true  )
	die();

if(!\Bitrix\Main\Loader::includeModule("iblock"))
	die;

class personalAccount extends CBitrixComponent
{
	public function __construct()
	{
		$this->arResult =
			[
				'status' => '',
				'answer' => '',
				'data'   => '',
			];
	}



	private function getUserById()
	{
		$request = \Bitrix\Main\Context::getCurrent()->getRequest();
		if(\Bitrix\Main\UserGroupTable::getList(['filter' => ['USER_ID' => $this->arParams['id'], 'GROUP.ACTIVE' => 'Y'],])->fetch())
		{
			$this->arResult['status'] = 'true';
		}
		$this->arResult['status'] = 'false';
	}

	public function executeComponent()
	{

		$this->getUserById();
		$this::IncludeComponentTemplate(); // TODO: Change the autogenerated stub
	}

}